### ISSUE TITLE
curses compatibility

### ISSUE THREAD

**Issue by ENDERZOMBI102** [DarviL82/PBar#15]
## Its is fantastic, but...
I use curses, and that might make pbar just give up on doing anything..

## So, i would like
The possibility to draw the bar on curses instead of just in "a terminal"

## As an end
I would like to say that, if necessary, i can implement this and then PR it, but if you want to tackle this, and if you're on windows
you might need to check out [windows-curses](https://pypi.org/project/windows-curses/)

**Comment by DarviL82** [comment]
What improvements could curses bring to the project exactly?
Also, what do you mean that pbar might give up?

**Comment by ENDERZOMBI102** [comment]
> What improvements could curses bring to the project exactly?
My idea was just basic curses support, so i could use it in a curses-based cli app

> Also, what do you mean that pbar might give up?
By "might give up" i mean this:

![image](https://user-images.githubusercontent.com/36399599/146327120-8afad042-db73-4dcc-b59d-e045d561944b.png)
After i quit the application, it shows up the bar
The code is visible behind the console

**Comment by DarviL82** [comment]
I honestly have no idea about how curses works. If you wish to try to make it work, go ahead :)
By the looks of it, seems like curses creates a second buffer, and then any text sent to stdout gets printed on the original one. This might be fixable if we use `sys.stdout.write()` instead of just doing a `print()`. I have no idea though so I'm just guessing :trollface:

**Comment by DarviL82** [comment]
`utils.out()` now writes directly to `stdout`. Assuming this is probably fixed.
Please consider reopenning this issue if the bar still does not show up.
